#!/bin/bash

sudo dnf install git \
                 vim \
                 pygobject2 \
                 python3 \
                 python3-pip \
                 pass \
                 owncloud-client \
                 chromium \
                 yum-plugin-fastestmirror \
                 irssi \
                 htop \
                 devhelp \
                 autoconf \
                 automake \
                 gettext-devel \
                 yelp-tools \
                 docbook-style-xsl \
                 libxml2-python \
                 glib-devel \
                 dbus-glib-devel \
                 libssh2-devel \
                 llvm-devel \
                 clang-devel \
                 ncurses-devel \
                 gobject-introspection-devel \
                 ostree-devel \
                 fuse-devel \
                 json-glib-devel \
                 libseccomp-devel \
                 libdwarf-devel \
                 @development-tools \
                 @c-development \
                 dbus-python \
                 redhat-rpm-config \
                 gnome-common \
                 perl-Text-CSV \
                 perl-XML-Parser \
                 sloccount \
                 glib2-devel \
                 git-bz \
                 jsoncpp-devel \
                 pcre2-devel \
                 e2fsprogs-libs \
                 rubygem-sass \
                 webkitgtk4-devel \
                 sysprof-devel \
                 mm-common \
                 glib-networking \
                 cvs \
                 subversion \
                 flex \
                 bison \
                 elfutils-libelf-devel \
                 thunderbird \
                 dconf-editor \
                 ninja-build \
                 qrencode \
                 libcroco-devel \
                 valgrind-devel \
                 libunwind-devel \
                 gstreamer-devel \
                 gobject-introspection-devel \
                 gnutls \
                 gtk-doc \
                 gstreamer1 \
                 gstreamer1-vaapi \
                 libarchive-devel \
                 e2fsprogs \
                 e2fsprogs-libs \
                 e2fsprogs-static \
                 auto-buildrequires \
                 ostree-devel \
                 gpgme-devel \
                 libdwarf-devel \
                 thefuck \
                 flatpak \
                 flatpak-builder
